
import type { Metadata } from "next";
import Sidebar from "../components/shared/Sidebar";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen">
      <div className="flex justify-between gap-4">
        <div className="md:w-[20%]   max-h-screen">
          <Sidebar />
        </div>
        <div className="md:w-[80%] lg:p-10 lg:px-16 rounded-xl lg:ml-6">{children}</div>
      </div>
    </div>
  );
}