
import type { Metadata } from "next";
import Sidebar from "../components/shared/Sidebar";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen">
      <div className="flex justify-between gap-4">
        <div className="w-[20%] bg-zinc-200 dark:bg-zinc-800 max-h-screen">
          <Sidebar />
        </div>
        <div className="w-[80%]  rounded-xl ml-2">{children}</div>
      </div>
    </div>
  );
}